# Generated by Django 2.2.9 on 2020-02-09 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200209_0049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverUser',
        ),
    ]
